# Starter pipeline


# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'
- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '11-Azure-Linux-Virtual-Machine/terraform-manifests'
    backendServiceArm: 'ARM_conn'
    backendAzureRmResourceGroupName: 'def_rg'
    backendAzureRmStorageAccountName: 'terrastoragesourish'
    backendAzureRmContainerName: 'terrascripts'
    backendAzureRmKey: 'tf/terraform.tfstate'
- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '11-Azure-Linux-Virtual-Machine/terraform-manifests'
    environmentServiceNameAzureRM: 'LTIM_CLOUDLAB_SUB'
- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '11-Azure-Linux-Virtual-Machine/terraform-manifests'
    environmentServiceNameAzureRM: 'LTIM_CLOUDLAB_SUB'


- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

